### ISSUE TITLE
"svmtool" on PowerShell for macOS?

### ISSUE THREAD

**Issue by mschindl** [oliviermasson/svmtool#27]
Hi Olivier,

is it possible to run your tool on PowerShell for macOS?

The challenge for me is to install NetApp PowerShell Toolkit on PowerShell for macOS. Any ideas?

Thank you and best regards, Marc

**Comment by oliviermasson** [comment]
Hi Marc,

As indicated this script does not work with Powershell Core.
To be more clear, it's not the script itself that is not compatible with Powershell Core, it's the NetApp  PowerShell ToolKit that is not compatible with Powershell Core.
PSTK is only available for Windows, with library compiled for Windows only.
And this script needs PSTK.
That's why this script does not work with other OS than Windows.

HTH
